recipes-images: packagegroups: pg-virtualization: Add fuse-overlayfs
We cannot run containers when the rootfs is mounted as nfs.

root@phyboard-lyra-am62xx-3:~# podman run 192.168.3.10:5000/hello-world:latest
Error: kernel does not support overlay fs: 'overlay' is not supported over \
  nfs at "/var/lib/containers/storage/overlay": backing file system is \
  unsupported for this graph driver

Podman requires to have fuse-overlayfs installed for that use-case. Add this
package to enable containers on a NFS mounted rootfs.

Signed-off-by: Daniel Schultz <d.schultz@phytec.de>
Reviewed-by: Leonard Anderweit <l.anderweit@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>