ampliphy-boot: net_boot_fit: Skip the initramfs bundled in the FIT
With the net boot script we want to use the NFS root. But the k3 fitImage
bundles an initramfs. And the bootm takes it from the FIT config which
makes the kernel boot it instead of NFS root.

Explicitly pass "-" to skip the ramdisk similar to mmc_boot.cmd.

This fixes our current PTF tests:

AssertionError: Wrong rootfs device. Expected '192.168.2.10:/srv/nfsroot', got 'rootfs'.
  assert 'rootfs' == '192.168.2.10:/srv/nfsroot'
    - 192.168.2.10:/srv/nfsroot
    + rootfs

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>