opencv: Fix C++ examples install
The opencv path in /usr/share changed from OpenCV to opencv4. This needs
to be fixed when installing C++ examples.

While at it, instead of installing the C++ example binaries manually use
the existing CMake options for that.

Fixes following build error:
ERROR: opencv-4.5.1-r0 do_package: QA Issue: opencv: Files/directories
were installed but not shipped in any package:
  /usr/share/OpenCV/samples/bin/example_structured_light_pointcloud
  /usr/share/OpenCV/samples/bin/example_datasets_ar_hmdb
  /usr/share/OpenCV/samples/bin/example_intensity_transform_intensity_transform
  ...
  /usr/share/OpenCV/samples/bin/example_xfeatures2d_pct_webcam
  /usr/share/OpenCV/samples/bin/example_ximgproc_deriche_demo
Please set FILES such that these items are packaged. Alternatively if they
are unneeded, avoid installing them or delete them within do_install.
opencv: 181 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Stefan Riedmueller <s.riedmueller@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>