recipes-core: rauc: Add runtime dependency on e2fsprogs-resize2fs
resize2fs is missing on a minimal system leading to the error during a
RAUC update:

LastError: Installation error: Failed updating slot rootfs.1: Failed to
run resize2fs: Failed to execute child process ?resize2fs? (No such file
or directory)

Add it for machines with an emmc.

Signed-off-by: Leonard Anderweit <l.anderweit@phytec.de>
Reviewed-by: Martin Schwan <m.schwan@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>