distro: common.inc: move to DISTRO_FEATURES_DEFAULTS
Fix error:
ERROR: Variable DISTRO_FEATURES_DEFAULT is obsolete, add all default
features to DISTRO_FEATURES_DEFAULTS (file:
[...]/meta-ampliphy/conf/distro/include/common.inc
line: 84 referenced as: DISTRO_FEATURES_DEFAULT:remove) ERROR: Variable
by using suggested solution:
DISTRO_FEATURES_DEFAULT is obsolete, add all default features to DISTRO_FEATURES_DEFAULTS

oe-core commit 159148f4de25 ("meta: Support opting out of any distro features")
introduced the change.
This commit also replaced DISTRO_FEATURES_BACKFILL_CONSIDERED, so follow
suit by renaming to DISTRO_FEATURES_OPTED_OUT

Signed-off-by: Yannic Moog <y.moog@phytec.de>
Reviewed-by: Wadim Egorov <w.egorov@phytec.de>
Tested-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>