phytec-base-bundle: Change imgtype of boot image archive
Change the imgtype of the boot image archive to be "boot" instead of
"file". Using imgtype "file" would result in the archive being suffixed
with ".img" before adding it to the RAUC bundle:

    [image.boot]
    sha256=fdb7d24e37333e84af7708ab02a35b50f6f560b474dbc2bf144eb71bc43ce09c
    size=13247965
    filename=boot.tar.gz.img

However since RAUC version 1.10 this will cause an error during bundle
installation, as the type is now interpreted as ".img" instead of
".tar.gz":

    LastError: Installation error: Failed updating slot boot.0: failed
    to splice data to tar: Broken pipe

With imgtype "boot" the archive will not be renamed.

Signed-off-by: Martin Schwan <m.schwan@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>