recipes-core: systemd: Enable cgroupv2 config
Compile systemd with default-hierarchy=unified for cgroupv2.
Note: The same option can be set by passing
  systemd.unified_cgroup_hierarchy=true
to the kernel command line.

This option will be removed in future systemd versions.

Fixes BSPAM62-1472:
  podman run --tls-verify=False 192.168.3.10:5000/hello-world:latest
  Error: OCI runtime error: crun: cgroups in hybrid mode not supported, drop all controllers from cgroupv2

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Reviewed-by: Leonard Anderweit <l.anderweit@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>