recipes-images: packagegroup-sks-openssl-tpm2: Mark TUNE_PKGARCH specific
Change Fix from Workaround to TUNE_PKGARCH:
ERROR: packagegroup-sks-openssl-tpm2-1.0-r0
do_package_write_ipk: An allarch packagegroup shouldn't
depend on packages which are dynamically renamed
- libtss2-tcti-device to libtss2-tcti-device-0
- libtss2-tcti-mssim to libtss2-tcti-mssim-0

Signed-off-by: Maik Otto <m.otto@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>