recipes-images: images: phytec-initramfs-image: Override IMAGE_FSTYPES for RAUC
Similar to the fix in e69d573f4381 ("recipes-images: images:
phytec-secureboot-initramfs: Override IMAGE_FSTYPES for RAUC").

RAUC without secureboot uses the partup FSTYPE set from the machine
config. This also sets the IMAGE_FSTYPES here which is not wanted.
Override back to INITRAMFS_FSTYPES.

Fixes:
  ERROR: 6742 unbuildable tasks were found
  These are usually caused by circular dependencies and any circular dependency chains
  found will be printed below. Increase the debug level to see a list of unbuildable tasks.

Suggested-by: Leonard Anderweit <l.anderweit@phytec.de>
Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Reviewed-by: Leonard Anderweit <l.anderweit@phytec.de>