distro: yogurt-vendor-xwayland: Remove opencv PREFERRED_VERSION
Since the v.5.4.70_2.3.0 release NXP has two versions of the opencv
recipe in their layer. One seems to be a copy of the upstream recipe
(4.4.0) and the other adds some NXP specific stuff (4.4.0.imx).

PREFERRED_VERSION = "4.%" leads to the selection of the 4.4.0 version
since both recipes are in the same layer and it is the first one to be
checked.

This is wrong because 4.4.0.imx > 4.4.0 and we actually want the NXP
version to be selected.

So we could either change the PREFERRED_VERSION or since there are only
version 4 recipes available for opencv anyway, we can just drop the
PREFERRED_VERSION completely.

This fixes following build issue of the ml-security package which
depends on the NXP version of opencv:

    ERROR: ml-security-1.0.3-r0 do_package_qa: QA Issue:
    /usr/share/ml-security/examples/cloning_sample contained in package
    ml-security requires libopencv_dnn.so.4.4()(64bit), but no providers
    found in RDEPENDS_ml-security? [file-rdeps]

ml-security is required for NXPs machine learning libraries.

Signed-off-by: Stefan Riedmueller <s.riedmueller@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>