conf: distro: remove EXTRA_IMAGE_FEATURES and EXTRAOPKGCONFIG
Remove EXTRA_IMAGE_FEATURES in yogurt's distro config. From the yocto
documentation:

  EXTRA_IMAGE_FEATURES:
  The list of additional features to include in an image. Configure this
  variable in the conf/local.conf file in the Build Directory.

Also remove the variable EXTRAOPKGCONFIG.

These changes fixes a bug, when a developer doesn't set
EXTRA_IMAGE_FEATURES in his local.conf like

    #EXTRA_IMAGE_FEATURES = "debug-tweaks"

as it is explained in the documentation. In this case the build fails
and shows the error:

    ERROR: Nothing RPROVIDES 'yogurt-feed-config-opkg' (but
    phytec-qt5demo-image.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Stefan Christ <s.christ@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>