phytec-camera-examples-imx95: Remove manual S variable setting
Remove the manual setting of the S variable as it is no longer required
for git sources and even causes a build failure.

Fixes following build error:
ERROR: phytec-camera-examples-imx95-0.1-r0 do_unpack:
Recipes that set S = "${WORKDIR}/git" or S = "${UNPACKDIR}/git" should remove
that assignment, as S set by bitbake.conf in oe-core now works.

Signed-off-by: Stefan Riedmüller <s.riedmueller@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>