packagegroup-sks-pkcs11-tpm2: Mark TUNE_PKGARCH specific
Fixes:
ERROR: packagegroup-sks-pkcs11-tpm2-1.0-r0
do_package_write_ipk: An allarch packagegroup shouldn't
depend on packages which are dynamically renamed
(libp11 to libp11-3)

Signed-off-by: Norbert Wesp <n.wesp@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>