recipes-images: Fix fitImage do_deploy conflict
Fix the fitImage do_deploy collision after linux-yocto-fitimage migration.
A fitImage is no longer a supported KERNEL_IMAGETYPE so we can remove
the check. This was pulling in a dependency to our legacy fitimage and
caused a conflict for K3 machines:

  ERROR: phytec-secureboot-initramfs-fitimage-1.0-r0 do_deploy: Recipe
  phytec-secureboot-initramfs-fitimage is trying to install files into a
  shared area when those files already exist:
    deploy-securiphy/images/phyboard-lyra-am62xx-4/fitImage
    (matched in manifest-phyboard_lyra_am62xx_4-linux-yocto-fitimage.deploy)

Keep the do_image dep only for imx6 and imx6ul, all other platforms
moved to linux-yocto-fitimage.

Also drop the UBOOT_SIGN_ENABLE guard, the FIT is required by secureboot,
not signing. And rename FITIMAGE_TO_WIC to something more meaningful,
the check has nothing to do with wic.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>