systemd: remove obsolete patch
Remove systemd IPv6 patch in meta-yogurt, because it's integrated in
poky in the branch fido now. If the patch is not remove, users get build
errors like

  ERROR: Command Error: exit status: 1  Output:
  Applying patch
  0060-gcc-var-tracking.c-backport-from-gcc-trunk-r212178.patch
  patching file gcc/var-tracking.c
  Hunk #1 FAILED at 5997.
  1 out of 1 hunk FAILED -- rejects in file gcc/var-tracking.c
  Patch 0060-gcc-var-tracking.c-backport-from-gcc-trunk-r212178.patch can
  be reverse-applied

when they make a current internal development checkout or a public work
in progress checkout with

    $ ./phyLinux init -p imx6 -r fido            # for costumers
    $ ./phyLinux init -p imx6 -r fido-next --dev # internal

Signed-off-by: Stefan Christ <s.christ@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>